module.exports = {
  black: '#33333e',
  'ex-dk-gray': '#21212a',
  'dk-gray': '#979797',
  'md-dk-gray': '#4c4c5b',
  'md-gray': '#ccc',
  'lt-md-gray': '#f8f8f8',
  'cb-lt-md-gray': '#A5A5A5',
  'lt-gray': '#f8f8f8',
  'md-lt-gray': '#d8d8d8',
  'ex-lt-gray': '#f1f1f1',
  'cb-ex-lt-gray': '#E8E8E8',
  white: '#fff',

  'mega-nav-bg': '#dbdbdb',
  'mega-nav-cat-hover': '#aaaaaa',
  'mega-nav-column-border': 'transparent',
  'mega-nav-subnav-bg': '#ffffff',
  'mega-nav-subcat-header-border': 'transparent',
  'mega-nav-cat-link-color': '#33333D',
  'mega-nav-box-shadow-color': '#cccccc',
  'mega-nav-subcat-header-color': '#33333e',
  'mega-nav-subcat-item-link-hover-color': '#ffffff',

  'success-color': '#36A943',
  terracotta: '#DB6C56',
  'terracotta-lt': '#fef3f0',
  'promocode-color': '#77B7B0',

  'highlight-color': '#ff6600',
  'highlight-secondary-color': '#ff4700',
  'error-color': '#D0021B',

  'user-locator--color': '#ff6600',
}
