export const RESET_SESSION_EXPIRED = 'RESET_SESSION_EXPIRED'
export const SESSION_EXPIRED = 'SESSION_EXPIRED'
export const SHOW_SESSION_EXPIRED_MESSAGE = 'SHOW_SESSION_EXPIRED_MESSAGE'
export const HIDE_SESSION_EXPIRED_MESSAGE = 'HIDE_SESSION_EXPIRED_MESSAGE'
