import {
  stringTypePattern,
  stringTypeNumber,
  numberType,
  stringType,
  arrayType,
  booleanType,
  objectType,
  booleanTypeAny,
} from '../utilis'

export const validGiftcardSchema = {
  title: 'gift card => valid',
  type: 'object',
  required: [
    'giftCardId',
    'giftCardNumber',
    'balance',
    'amountUsed',
    'remainingBalance',
  ],
  properties: {
    giftCardId: stringTypeNumber,
    giftCardNumber: stringTypePattern('XXXX XXXX 0830'),
    balance: stringTypePattern('[0-9]'),
    amountUsed: stringTypePattern('[0-9]'),
    remainingBalance: stringTypePattern('[0-9]'),
  },
}

export const orderSummarySchemaBasket = {
  title: 'Order Summary Gift Card => Basket',
  type: 'object',
  required: [
    'orderId',
    'subTotal',
    'total',
    'totalBeforeDiscount',
    'deliveryOptions',
    'promotions',
    'discounts',
    'products',
    'savedProducts',
    'ageVerificationRequired',
    'restrictedDeliveryItem',
    'inventoryPositions',
    'isDDPOrder',
    'isBasketResponse',
    'isOrderCoveredByGiftCards',
    'deliveryThresholdsJson',
  ],
  optional: [
    'isGuestOrder',
    'isClearPayAvailable',
    'isGiftCardRedemptionEnabled',
    'isGiftCardValueThresholdMet',
    'giftCardRedemptionPercentage',
  ],
  properties: {
    isGuestOrder: booleanType(false),
    orderId: numberType,
    subTotal: stringType,
    total: stringType,
    totalBeforeDiscount: stringType,
    deliveryOptions: arrayType(),
    promotions: arrayType(),
    discounts: arrayType(),
    products: arrayType(1),
    savedProducts: arrayType(),
    ageVerificationRequired: booleanType(false),
    restrictedDeliveryItem: booleanType(false),
    inventoryPositions: objectType,
    isDDPOrder: booleanType(false),
    isBasketResponse: booleanType(true),
    isOrderCoveredByGiftCards: booleanType(false),
    deliveryThresholdsJson: stringType,
    isClearPayAvailable: booleanTypeAny,
    isGiftCardRedemptionEnabled: booleanTypeAny,
    isGiftCardValueThresholdMet: booleanTypeAny,
    giftCardRedemptionPercentage: numberType,
  },
}
