export const completedOrder = {
  OrderConfirmation: {
    orderId: 9365511,
    currencyCode: 'GBP',
    orderItems: [
      {
        orderItemId: '10673568',
        selectedShipCode: 'S',
        deliveryCarrier: 'Standard',
        selectedDeliveryMethod: 'UK Standard up to 5 days',
        description1: 'Up to 5 days',
        description2: '',
      },
    ],
    deliveryMethod: 'UK Standard up to 5 days',
    smsMobileNumber: '07872446040',
    deliveryDetails: {
      nameAndPhone: {
        title: 'Mr',
        firstName: 'Test',
        lastName: 'Tester',
        telephone: '07872446041',
      },
      AddressDetails: {
        city: 'LONDON',
        country: 'United Kingdom',
        address1: '9 Waldegrave Road',
        zipCode: 'W5 3HT',
        addressDetailsId: '3547333',
        shippingDescription: 'UK Standard up to 5 days',
        estimatedDelivery: 'No later thanMonday 15 April 2019',
      },
    },
    billingDetails: {
      title: 'Mr',
      lastName: 'Tester',
      firstName: 'Test',
      city: 'LONDON',
      country: 'United Kingdom',
      address1: '9 Waldegrave Road',
      address2: '',
      zipCode: 'W5 3HT',
    },
    giftCardMsg: '',
    creditCardList: 'AMEX,VISA,MCARD,ACCNT,SWTCH',
    creditCard: {
      selectedPaymentMethod: 'VISA',
      paymentDetailsText: 'Payment Details',
      orderTotalText: 'Order Total',
      grandTotalAmount: 45.95,
      type: '',
      cardText: ' card - ',
      cardNumberStar: 'XXXX XXXX XXXX 1111',
      paymentAmount: 11.3,
      CARD_BRAND_TEXT: 'Visa',
    },
    giftCards: [
      {
        giftCardLabel: 'Gift Card',
        giftCardLabelValueSeparator: ' - ',
        giftCardNumber: 'XXXX XXXX XXXX 6399',
        giftCardDeposit: 34.65,
        giftCardId: '11138344',
        pin: '1122',
        remainingBalance: '0.00',
        amountUsed: 34.65,
        balance: '34.65',
      },
    ],
    giftCardMessageContent: '',
  },
}

export const completedGiftCardOrder = {
  OrderConfirmation: {
    orderId: 9366082,
    currencyCode: 'GBP',
    orderItems: [
      {
        orderItemId: '10674211',
        selectedShipCode: 'S',
        deliveryCarrier: 'Standard',
        selectedDeliveryMethod: 'UK Standard up to 5 days',
        description1: 'Up to 5 days',
        description2: '',
      },
    ],
    deliveryMethod: 'UK Standard up to 5 days',
    smsMobileNumber: '07872446040',
    deliveryDetails: {
      nameAndPhone: {
        title: 'Mr',
        firstName: 'Hisham',
        lastName: 'El-sayed',
        telephone: '07872446040',
      },
      AddressDetails: {
        city: 'LONDON',
        country: 'United Kingdom',
        address1: '9 Waldegrave Road',
        zipCode: 'W5 3HT',
        addressDetailsId: '3547333',
        shippingDescription: 'UK Standard up to 5 days',
        estimatedDelivery: 'No later thanMonday 15 April 2019',
      },
    },
    billingDetails: {
      title: 'Mr',
      lastName: 'El-sayed',
      firstName: 'Hisham',
      city: 'LONDON',
      country: 'United Kingdom',
      address1: '9 Waldegrave Road',
      address2: '',
      zipCode: 'W5 3HT',
    },
    giftCardMsg: '',
    creditCardList: 'AMEX,VISA,MCARD,ACCNT,SWTCH',
    creditCard: {
      selectedPaymentMethod: 'GCARD',
      paymentDetailsText: 'Payment Details',
      orderTotalText: 'Order Total',
      grandTotalAmount: 8.95,
      type: '',
      CARD_BRAND_TEXT: 'Gift Card',
    },
    giftCards: [
      {
        giftCardLabel: 'Gift Card',
        giftCardLabelValueSeparator: ' - ',
        giftCardNumber: 'XXXX XXXX XXXX 8361',
        giftCardDeposit: 8.95,
        giftCardId: '11142141',
        pin: '1216',
        remainingBalance: '43.35',
        amountUsed: 34.4,
        balance: '52.30',
      },
    ],
    giftCardMessageContent: '',
  },
}
