variable "certificate_arn" {}
variable "newrelic_app_name" {}
variable "newrelic_key" {}
variable "app_config_tablename" {}
variable "access_key_id_dynamodb" {}
variable "secret_access_key_dynamodb" {}
variable "sns_topic_arn_app_config" {}
variable "service_role" {}
variable "instance_profile" {}
variable "instance_type" {}
variable "keypair_name" {}
variable "asg_min_size" {}
variable "asg_max_size" {}
variable "environment_name" {}
variable "ec2_security_group" {}
variable "elb_security_group_ids" {}
variable "vpc_id" {}
variable "subnet_ids" {}
