export default [
  'Albania',
  'Andorra',
  'Anguilla',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bangladesh',
  'Barbados',
  'Belgium',
  'Bermuda',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Brunei',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'China',
  'Colombia',
  'Cook Islands',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Eritrea',
  'Estonia',
  'Falkland Islands',
  'Faroe Islands',
  'Finland',
  'France',
  'French Guiana',
  'Gambia',
  'Germany',
  'Greece',
  'Greenland',
  'Guadeloupe',
  'Guernsey',
  'Guyana',
  'Holy See',
  'Hong Kong S.A.R. of China',
  'Hungary',
  'India',
  'Indonesia',
  'Ireland',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea South',
  'Kyrgyzstan',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau S.A.R. of China',
  'Madagascar',
  'Malaysia',
  'Maldives',
  'Marshall Islands',
  'Mexico',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Morocco',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Niger',
  'Pakistan',
  'Panama',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Romania',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Serbia',
  'Seychelles',
  'S Georgia & S Sandwich Islands',
  'Singapore',
  'Slovakia',
  'Solomon Islands',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'St Vincent and the Grenadines',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Thailand',
  'Togo',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Vanuatu',
  'Vietnam',
  'Virgin Islands British',
]

export const shippingExceptions = {
  ts: ['Romania'],
}
