export default {
  response: {
    body: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred',
    },
    files: {},
    buffered: true,
    headers: {
      'x-frame-options': 'SAMEORIGIN',
      'content-type': 'application/json; charset=utf-8',
      'x-xss-protection': '1; mode=block',
      'x-download-options': 'noopen',
      'x-content-type-options': 'nosniff',
      'set-cookie': [Array],
      'cache-control': 'no-cache',
      vary: 'accept-encoding',
      'content-encoding': 'gzip',
    },
    statusCode: 500,
    status: 500,
    statusType: 5,
    info: false,
    ok: false,
    redirect: false,
    clientError: false,
    serverError: true,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: false,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    charset: 'utf-8',
    type: 'application/json',
    redirects: [],
    text:
      '{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}',
  },
}
