export default {
  body: {
    orderId: 8356706,
    subTotal: '38.00',
    statusCode: 'C',
    status: 'Your order is currently being packed by our warehouse.',
    returnPossible: false,
    returnRequested: false,
    deliveryMethod: 'Tuesday Nominated Day Delivery:',
    deliveryDate: 'Tuesday 9 July 2019',
    deliveryCost: '',
    deliveryCarrier: 'Home Delivery Network',
    deliveryPrice: '0.00',
    isDDPOrder: false,
    totalOrderPrice: '38.00',
    totalOrdersDiscount: '',
    totalOrdersDiscountLabel: 'Discounts',
    billingAddress: {
      name: 'Mr 3D. AUTHORISED',
      address1: 'Test Street',
      address2: '',
      address3: 'Manchester',
      address4: 'M3 1NL',
      country: 'United Kingdom',
    },
    deliveryAddress: {
      name: 'Mr 3D. AUTHORISED',
      address1: 'Test Street',
      address2: '',
      address3: 'Manchester',
      address4: 'M3 1NL',
      country: 'United Kingdom',
    },
    orderLines: [{}],
    paymentDetails: [[{}]],
    smsNumber: '',
  },
  files: {},
  buffered: true,
  headers: {
    'x-frame-options': 'SAMEORIGIN',
    'content-type': 'application/json; charset=utf-8',
    'x-xss-protection': '1; mode=block',
    'x-download-options': 'noopen',
    'x-content-type-options': 'nosniff',
    'set-cookie': [
      'jsessionid=eyJhbGciOiJIUzI1NiJ9.ZWIyMDhlNTYtYzIwYS00ZDVlLTg1NDQtMTQzNGNjMjNkNGYy.It9MpOGDDhP9Zd5Fc3wgPk8IkUkeBoG7o1ODw_E2g2M; Max-Age=432000; Expires=Sun, 14 Jul 2019 11:17:53 GMT; HttpOnly; Path=/',
      'source=CoreAPI; Path=/',
      'tempsession=true; Max-Age=1800; Expires=Tue, 09 Jul 2019 11:47:53 GMT; HttpOnly; Path=/',
    ],
    vary: 'accept-encoding',
    'content-encoding': 'gzip',
    'x-newrelic-app-data':
      'PxQGUldaCwQIR1BaBwUDVFQGAxFORDQHUjZKA1ZLVVFHDFYPHilSEg0ZcCQyTBdSQA1OA1RSWBMKRRlcEAIGEB0KURFMV0ZLHB5WE1UEQSsASxVNVk8IHQZVUFMABw5fSBwHH0BVB1NTWl1aCA0MVwRdC0MdB1IOF1Nq',
    date: 'Tue, 09 Jul 2019 11:17:53 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  header: {
    'x-frame-options': 'SAMEORIGIN',
    'content-type': 'application/json; charset=utf-8',
    'x-xss-protection': '1; mode=block',
    'x-download-options': 'noopen',
    'x-content-type-options': 'nosniff',
    'set-cookie': [
      'jsessionid=eyJhbGciOiJIUzI1NiJ9.ZWIyMDhlNTYtYzIwYS00ZDVlLTg1NDQtMTQzNGNjMjNkNGYy.It9MpOGDDhP9Zd5Fc3wgPk8IkUkeBoG7o1ODw_E2g2M; Max-Age=432000; Expires=Sun, 14 Jul 2019 11:17:53 GMT; HttpOnly; Path=/',
      'source=CoreAPI; Path=/',
      'tempsession=true; Max-Age=1800; Expires=Tue, 09 Jul 2019 11:47:53 GMT; HttpOnly; Path=/',
    ],
    'cache-control': 'no-cache',
    vary: 'accept-encoding',
    'content-encoding': 'gzip',
    'x-newrelic-app-data':
      'PxQGUldaCwQIR1BaBwUDVFQGAxFORDQHUjZKA1ZLVVFHDFYPHilSEg0ZcCQyTBdSQA1OA1RSWBMKRRlcEAIGEB0KURFMV0ZLHB5WE1UEQSsASxVNVk8IHQZVUFMABw5fSBwHH0BVB1NTWl1aCA0MVwRdC0MdB1IOF1Nq',
    date: 'Tue, 09 Jul 2019 11:17:53 GMT',
    connection: 'close',
    'transfer-encoding': 'chunked',
  },
  statusCode: 200,
  status: 200,
  statusType: 2,
  info: false,
  ok: true,
  redirect: false,
  clientError: false,
  serverError: false,
  error: false,
  accepted: false,
  noContent: false,
  badRequest: false,
  unauthorized: false,
  notAcceptable: false,
  forbidden: false,
  notFound: false,
  charset: 'utf-8',
  type: 'application/json',
  setEncoding: [],
  redirects: [],
}
