module.exports = {
  'dk-gray': '#232323',
  'md-dk-gray': '#666',
  'md-gray': '#ccc',
  'lt-md-gray': '#d8d8d8',
  'cb-lt-md-gray': '#A5A5A5',
  'lt-gray': '#f8f8f8',
  'ex-lt-gray': '#E8E8E8',
  white: '#fff',
  black: '#000',
  'error-color': '#D0021B',
  'success-color': '#36A943',
  'promocode-color': '#36A943',

  'mega-nav-bg': '#fff',
  'mega-nav-cat-color': '#000',
  'mega-nav-subnav-bg': '#e7e7e7',
  'mega-nav-cat-hover': '#ccc',
  'mega-nav-subcat-header-border': '#777',
  'mega-nav-subcat-header-color': '#777',
  'mega-nav-subcat-hover-color': '#999',
  'mega-nav-column-border': '#e6e6e6',

  'now-price-red': '#db3f40',
  'was-price-black': '#232323',
}
