apiVersion: v1
kind: Service
metadata:
  name: coreapi
  labels:
    app: monty
spec:
  ports:
    - port: 80
      targetPort: monty-port
  selector:
    app: monty
    tier: monty_coreapi
  type: LoadBalancer
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: coreapi
  labels:
    app: monty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monty
      tier: monty_coreapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monty
        tier: monty_coreapi
    spec:
      containers:
      - image: arcadiagroup/full-monty:v3.16.1
        name: full-monty
        resources:
          requests:
            memory: "1500Mi"
        env:
        - name: NEWRELIC_APP_NAME
          value: monty-production-eks
        - name: NEWRELIC_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-prod-key
              key: key
        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"
        - name: APP_CONFIG_SNS_TOPIC_ARN
          value: arn:aws:sns:eu-west-1:330032770480:appConfig_production
        - name: APP_CONFIG_TABLENAME
          value: production_coreapi_eks
        - name: ENVIRONMENT_NAME
          value: production_coreapi
        - name: CONTAINER_SNS_PORT
          value: 9001
        ports:
        - containerPort: 3000
          name: monty-port
          protocol: TCP
        - containerPort: 9000
          name: admin-port
          protocol: TCP
      imagePullSecrets:
      - name: regcred