variable "aws_region" { default = "eu-west-1" }
variable "vpc_cidr_block" { default = "172.16.0.0/16" }
variable "subnet_a_cidr_block" { default = "172.16.64.0/18" }
variable "subnet_b_cidr_block" { default = "172.16.128.0/18" }
variable "subnet_c_cidr_block" { default = "172.16.192.0/18" }
variable "certificate_arn" { description = "ARN of the certificate to be used by the load balancer" }
variable "newrelic_app_name" { description = "The name of the app on New Relic monitoring" }
variable "newrelic_key" { description = "Key for New Relic monitoring" }
variable "app_config_tablename" { description = "The dynamodb table name that Monty gets its appConfig env variables from" }
variable "instance_type" { description = "The EC2 instance type" }
variable "keypair_name" { description = "The AWS keypair name to use as default ssh key" }
variable "asg_min_size" { description = "Minimum size of instances on autoscaling group" }
variable "asg_max_size" { description = "Maximum size of instances on autoscaling group" }
variable "environment_name" { description = "The name of the elastic beanstalk environment" }
variable "elasticbeanstalk_s3_bucket" { description = "The name of the s3 bucket to use for elastic beanstalk" }
variable "dockerhub_auth" { description = "The auth token for dockerhub" }
variable "arcadia_cidrs" { description = "Comma separated list of Arcadia network CIDR blocks" }
variable "loadbalancer_allowed_cidrs_akamai_production" { description = "Comma separated list of Akamai production network CIDR blocks that are allowed to ingress in the load balancer security group" }
variable "loadbalancer_allowed_cidrs_akamai_staging" { description = "Comma separated list of Akamai staging network CIDR blocks that are allowed to ingress in the load balancer security group" }
variable "table_name_app_config" { description = "The dynamodb table name for the Monty application configuration" }
variable "read_capacity_app_config" { description = "The Monty application configuration dynamodb table read capacity" }
variable "write_capacity_app_config" { description = "The Monty application configuration dynamodb table write capacity" }
variable "hash_key_app_config" { description = "The Monty application configuration dynamodb table hash key" }
variable "attr_name_app_config" { description = "The Monty application configuration dynamodb table attribute name" }
variable "sns_topic_name_app_config" { description = "The Monty SNS Topic application configuration name" }
variable "sns_topic_display_name_app_config" { description = "The Monty SNS Topic application configuration display name" }
variable "jenkins_master_key_name" { description = "The name of the keypair on aws for ssh into jenkins master"}
variable "jenkins_master_instance_type" { description = "The instance type for jenkins master" default = "t2.small"}
variable "jenkins_ami_id" { description = "The AWS AMI to use for jenkins master"}
